default:
  trainer: ppo
  batch_size: 10
  beta: 5.0e-3
  buffer_size: 100
  epsilon: 0.2
  hidden_units: 128
  lambd: 0.95
  learning_rate: 3.0e-4
  learning_rate_schedule: linear
  max_steps: 5.0e6
  memory_size: 128
  normalize: false
  num_epoch: 3
  num_layers: 2
  self_play:
    window: 10
    play_against_latest_model_ratio: 0.5
    save_steps: 10000
    swap_steps: 50000
    team_change: 50000
  sequence_length: 128
  summary_freq: 1000
  time_horizon: 64
  use_recurrent: false
  reward_signals:
    extrinsic:
      strength: 1.0
      gamma: 0.99

Sheep:
  trainer: ppo
  batch_size: 2000
  beta: 5.0e-3
  buffer_size: 10000
  learning_rate: 3.0e-4

wolf:
  trainer: ppo
